version: "3.7"

services:
  db:
    image: ${PG_IMAGE}
    expose:
      - ${PG_EXPOSE}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ${PG_VOLUME}:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:${ES_TAG}
    ports:
      - "${ES_REST_PORT}"
      - "${ES_NODE_PORT}"
    environment:
      - bootstrap.memory_lock=${ES_MEMORY_LOCK}
      - discovery.type=${ES_DISCOVERY_TYPE}
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - cluster.routing.allocation.disk.threshold_enabled=${ES_TRESHOLD_ENABLED}
    volumes:
      - ${ES_VOLUME_DATA}:/etc/elasticsearch/data
      - ${ES_VOLUME_CONFIG}:/etc/elasticsearch/config/elasticsearch.yml
  app:
    build: .
    restart: always
    volumes:
      - .:/home/dewey
    depends_on:
      - db
