version: "3"

services:
  elasticsearch:
    image: elasticsearch:${ES_TAG}
    ports:
      - "${ES_REST_PORT}"
      - "${ES_NODE_PORT}"
    environment:
      - bootstrap.memory_lock=${ES_MEMORY_LOCK}
      - discovery.type=${ES_DISCOVERY_TYPE}
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - cluster.routing.allocation.disk.threshold_enabled=${ES_TRESHOLD_ENABLED}
    volumes:
      - ${ES_VOLUME_DATA}:/etc/elasticsearch/data
      - ${ES_VOLUME_CONFIG}:/etc/elasticsearch/config/elasticsearch.yml
    networks:
      - dewey_project

networks:
  dewey_project: