"""empty message

Revision ID: 987ec6109f13
Revises: 6981b8a55aec
Create Date: 2020-06-04 13:52:18.092651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987ec6109f13'
down_revision = '6981b8a55aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'articles', ['title', 'state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'updated_at')
    # ### end Alembic commands ###
