"""empty message

Revision ID: addd522b49ab
Revises: 987ec6109f13
Create Date: 2020-07-01 17:11:23.079997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addd522b49ab'
down_revision = '987ec6109f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'state',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint('articles_title_state_key', 'articles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('articles_title_state_key', 'articles', ['title', 'state'])
    op.alter_column('articles', 'state',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
