"""empty message

Revision ID: d5702b14b420
Revises: 6981b8a55aec
Create Date: 2020-05-29 15:38:30.690799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5702b14b420'
down_revision = '6981b8a55aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'articles', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'update_at')
    # ### end Alembic commands ###
