openapi: "3.0.0"
info:
  description: This is the openapi file that goes with our server code
  version: "0.1"
  title: Dewey project Open API

servers:
  - url: http://localhost:5000/doc/users


paths:
  /users/login:
    post:
      operationId: "webapp.users.views.LoginAPIView.post"
      tags:
        - "Users"
      summary: "Sign In"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "Successful sign in"
          content:
            application/json:
              schema:
                properties:
                  "status":
                    type: string
                    default: "success"
                    example: "success"
                  "message":
                    type: string
                    default: "Successfully logged in."
                    example: "Successfully logged in."
                  "auth_token":
                    type: string
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404_User'
        '500':
          description: Fail
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
  /users:
    post:
      operationId: "webapp.users.views.UserAPIView.post"
      tags:
        - "Users"
      summary: "User create"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                role:
                  type: object
                  properties:
                    title:
                      type: string
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    default: Created new user.
                    example: Created new user.
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Failed
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    default: No input data provided
                    example: No input data provided
        '422':
          description: Error
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string

components:
  schemas:
    Permission:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
    Role:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        created_at:
          type: string
          example:
            example: "2020-06-11T12:19:32.372Z"
        role:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    404_User:
      type: object
      properties:
        message:
          type: string
          example: Not exist.
          default: Not exist.
        status:
          type: string
          example: fail
          default: fail