openapi: "3.0.0"
info:
  description: This is the swagger file that goes with our server code
  version: "0.1"
  title: Dewey project Open API

servers:
  - url: http://localhost:5000/doc


paths:
  /:
    get:
      operationId: "webapp.core.views.index"
      tags:
        - "Core"
      summary: "Base endpoint"
      responses:
        '200':
          description: receives `index.html`
          content:
            application/json:
              schema:
                type: string
  /articles:
    get:
      operationId: "webapp.articles.views.ArticleAPIView.get"
      tags:
        - "Articles"
      summary: "Retrieve all articles"
      responses:
        '200':
          description: "Successful retrieve all articles"
          content:
            application/json:
              schema:
                type: object
                required:
                  - title
                  - cfr40_part280
                  - citation
                  - unique_id
                  - legal_language
                properties:
                  abstract:
                    type: string
                  cfr40_part280:
                    type: string
                  citation:
                    type: string
                  effective_date:
                    type: string
                    example: "2020-06-11"
                  id:
                    type: integer
                    readOnly: true
                  legal_language:
                    type: string
                  local_regulation:
                    type: string
                  reference_images:
                    type: string
                  state:
                    type: string
                  title:
                    type: string
                  unique_id:
                    type: string
                  updated_at:
                    type: string
                    example: "2020-06-11T12:19:32.372Z"
                  updated_date:
                    type: string
                    example: "2020-06-11"
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/IdNameSchema'
                  tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/IdNameSchema'
    post:
      operationId: "webapp.articles.views.ArticleAPIView.post"
      tags:
        - "Articles"
      summary: "Article create"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - cfr40_part280
                - citation
                - unique_id
                - legal_language
              properties:
                abstract:
                  type: string
                cfr40_part280:
                  type: string
                citation:
                  type: string
                effective_date:
                  type: string
                  example: "2020-06-11"
                legal_language:
                  type: string
                local_regulation:
                  type: string
                reference_images:
                  type: string
                state:
                  type: string
                title:
                  type: string
                unique_id:
                  type: string
                updated_at:
                  type: string
                  example: "2020-06-11T12:19:32.372Z"
                updated_date:
                  type: string
                  example: "2020-06-11"
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                tags:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
      responses:
        200:
          description: "Successful retrieve all articles"
  /articles/<article_id>:
    put:
      operationId: "webapp.articles.views.ArticleAPIView.put"
      tags:
        - "Articles"
      summary: "Article create"
      parameters:
        - name: article_id
          in: path
          required: true
          description: The id of the article to retrieve
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                abstract:
                  type: string
                cfr40_part280:
                  type: string
                citation:
                  type: string
                effective_date:
                  type: string
                  example: "2020-06-11"
                legal_language:
                  type: string
                local_regulation:
                  type: string
                reference_images:
                  type: string
                state:
                  type: string
                title:
                  type: string
                unique_id:
                  type: string
                updated_at:
                  type: string
                  example: "2020-06-11T12:19:32.372Z"
                updated_date:
                  type: string
                  example: "2020-06-11"
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                tags:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
      responses:
        200:
          description: "Successful retrieve all articles"
  /articles/<article_id>/download:
    get:
      operationId: "webapp.articles.views.DownloadArticleXLSView.get"
      tags:
        - "Articles"
      summary: "Article create"
      parameters:
        - name: article_id
          in: path
          required: true
          description: The id of the article to retrieve
          schema:
            type: integer
      responses:
        200:
          description: "Successful retrieve all articles"
  /users/login:
    post:
      operationId: "webapp.users.views.LoginAPIView.post"
      tags:
        - "Users"
      summary: "Sign In"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: "Successful retrieve all articles"
  /users:
    post:
      operationId: "webapp.users.views.UserAPIView.post"
      tags:
        - "Users"
      summary: "User create"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                role:
                  type: object
                  properties:
                    title:
                      type: string
      responses:
        200:
          description: "Successful retrieve all articles"


components:
  schemas:
    IdNameSchema:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string