# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export FLASK_APP=main.py
        export FLASK_ENV=development
    - name: Styles checking
      run: |
        isort
        black . --check --diff
        pylint --load-plugins pylint_flask_sqlalchemy webapp/
    - name: Test with pytest
      run: |
        export FLASK_APP=main.py
        export FLASK_ENV=development
        pytest webapp/articles
